"""Popular package names, used only for typo-distance comparison.

PyPI names come from the top-pypi-packages dataset. npm has no public top-list,
so those are the highest-download names from the registry's own download API,
seeded from popularity-ranked search results.

The lists exist to answer one question: does this young package look like a
typo of something people install a lot? Nothing else reads them.
"""

# 2000 most-downloaded PyPI projects
TOP_PYPI = frozenset([
    'a2a-sdk', 'a2wsgi', 'absl-py', 'accelerate', 'adal', 'addict', 'adlfs', 'aenum', 'affine',
    'ag-ui-protocol', 'agate', 'agent-client-protocol', 'aio-pika', 'aioboto3', 'aiobotocore',
    'aiocache', 'aiodns', 'aiofile', 'aiofiles', 'aiohappyeyeballs', 'aiohttp', 'aiohttp-cors',
    'aiohttp-retry', 'aioitertools', 'aiokafka', 'aiolimiter', 'aiomysql', 'aioquic',
    'aioresponses', 'aiormq', 'aiosignal', 'aiosmtplib', 'aiosqlite', 'alabaster', 'alembic',
    'alibabacloud-credentials', 'alibabacloud-tea-openapi', 'aliyun-semantic-conventions',
    'aliyun-trace', 'allure-pytest', 'allure-python-commons', 'altair', 'altgraph',
    'amazon-ion', 'amplitude-analytics', 'amqp', 'aniso8601', 'annotated-doc',
    'annotated-types', 'ansible', 'ansible-compat', 'ansible-core', 'ansicolors', 'anthropic',
    'antlr4-python3-runtime', 'anyio', 'anytree', 'apache-airflow', 'apache-airflow-core',
    'apache-airflow-providers-amazon', 'apache-airflow-providers-cncf-kubernetes',
    'apache-airflow-providers-common-compat', 'apache-airflow-providers-common-io',
    'apache-airflow-providers-common-sql', 'apache-airflow-providers-databricks',
    'apache-airflow-providers-fab', 'apache-airflow-providers-ftp',
    'apache-airflow-providers-google', 'apache-airflow-providers-http',
    'apache-airflow-providers-imap', 'apache-airflow-providers-mysql',
    'apache-airflow-providers-slack', 'apache-airflow-providers-smtp',
    'apache-airflow-providers-snowflake', 'apache-airflow-providers-sqlite',
    'apache-airflow-providers-ssh', 'apache-airflow-task-sdk', 'apache-tvm-ffi', 'apispec',
    'appdirs', 'applicationinsights', 'appnope', 'apprise', 'apscheduler', 'arabic-reshaper',
    'argcomplete', 'argon2-cffi', 'argon2-cffi-bindings', 'argparse', 'arro3-core', 'arrow',
    'arxiv', 'asgi-lifespan', 'asgiref', 'asn1crypto', 'ast-serialize', 'asteval', 'astor',
    'astroid', 'astronomer-cosmos', 'asttokens', 'astunparse', 'async-lru', 'async-timeout',
    'asyncer', 'asyncio', 'asyncpg', 'asyncssh', 'asynctest', 'atlassian-python-api',
    'atpublic', 'attrs', 'audioop-lts', 'audioread', 'auth0-python', 'authlib', 'autobahn',
    'autoflake', 'automat', 'autopep8', 'av', 'avro', 'avro-python3', 'aws-cdk-asset-awscli-v1',
    'aws-cdk-asset-node-proxy-agent-v6', 'aws-cdk-cloud-assembly-schema', 'aws-cdk-lib',
    'aws-lambda-powertools', 'aws-msk-iam-sasl-signer-python', 'aws-requests-auth',
    'aws-sam-translator', 'aws-xray-sdk', 'awscli', 'awscrt', 'awswrangler', 'azure-ai-agents',
    'azure-ai-documentintelligence', 'azure-ai-projects', 'azure-appconfiguration',
    'azure-batch', 'azure-cli', 'azure-cli-core', 'azure-common', 'azure-core',
    'azure-core-tracing-opentelemetry', 'azure-cosmos', 'azure-data-tables',
    'azure-datalake-store', 'azure-eventgrid', 'azure-eventhub', 'azure-functions',
    'azure-identity', 'azure-keyvault', 'azure-keyvault-certificates', 'azure-keyvault-keys',
    'azure-keyvault-secrets', 'azure-kusto-data', 'azure-kusto-ingest', 'azure-mgmt-advisor',
    'azure-mgmt-applicationinsights', 'azure-mgmt-authorization', 'azure-mgmt-batch',
    'azure-mgmt-batchai', 'azure-mgmt-billing', 'azure-mgmt-cdn',
    'azure-mgmt-cognitiveservices', 'azure-mgmt-compute', 'azure-mgmt-containerinstance',
    'azure-mgmt-containerregistry', 'azure-mgmt-containerservice', 'azure-mgmt-core',
    'azure-mgmt-cosmosdb', 'azure-mgmt-datafactory', 'azure-mgmt-datalake-nspkg',
    'azure-mgmt-datalake-store', 'azure-mgmt-datamigration', 'azure-mgmt-eventgrid',
    'azure-mgmt-eventhub', 'azure-mgmt-iotcentral', 'azure-mgmt-iothub',
    'azure-mgmt-iothubprovisioningservices', 'azure-mgmt-keyvault', 'azure-mgmt-loganalytics',
    'azure-mgmt-managementgroups', 'azure-mgmt-maps', 'azure-mgmt-marketplaceordering',
    'azure-mgmt-media', 'azure-mgmt-monitor', 'azure-mgmt-msi', 'azure-mgmt-network',
    'azure-mgmt-nspkg', 'azure-mgmt-policyinsights', 'azure-mgmt-rdbms',
    'azure-mgmt-recoveryservices', 'azure-mgmt-recoveryservicesbackup', 'azure-mgmt-redis',
    'azure-mgmt-resource', 'azure-mgmt-search', 'azure-mgmt-servicebus',
    'azure-mgmt-servicefabric', 'azure-mgmt-signalr', 'azure-mgmt-sql', 'azure-mgmt-storage',
    'azure-mgmt-trafficmanager', 'azure-mgmt-web', 'azure-monitor-opentelemetry',
    'azure-monitor-opentelemetry-exporter', 'azure-monitor-query', 'azure-nspkg',
    'azure-search-documents', 'azure-servicebus', 'azure-storage-blob', 'azure-storage-common',
    'azure-storage-file-datalake', 'azure-storage-file-share', 'azure-storage-queue',
    'azure-synapse-artifacts', 'azure-synapse-spark', 'babel', 'backcall', 'backoff',
    'backports-asyncio-runner', 'backports-strenum', 'backports-tarfile', 'backports-zoneinfo',
    'backports-zstd', 'backrefs', 'bandit', 'banks', 'basedpyright', 'bashlex',
    'bazel-runfiles', 'bcrypt', 'beartype', 'beautifulsoup4', 'bedrock-agentcore', 'behave',
    'bidict', 'billiard', 'binaryornot', 'biopython', 'bitarray', 'bitsandbytes', 'black',
    'blake3', 'bleach', 'blessed', 'blinker', 'blis', 'blobfile', 'bluetooth-data-tools',
    'bokeh', 'boltons', 'boolean-py', 'boostedblob', 'boto', 'boto3', 'boto3-stubs', 'botocore',
    'botocore-stubs', 'bottle', 'bottleneck', 'bracex', 'braintrust', 'brotli',
    'browser-harness', 'browser-use', 'browser-use-sdk', 'bs4', 'bubus', 'build',
    'burner-redis', 'bytecode', 'c7n-org', 'cachebox', 'cachecontrol', 'cached-property',
    'cachelib', 'cachetools', 'cadwyn', 'caio', 'cairocffi', 'cairosvg', 'cassandra-driver',
    'catalogue', 'catboost', 'cattrs', 'cbor2', 'cchardet', 'cdp-use', 'cel-python', 'celery',
    'celery-redbeat', 'cerberus', 'certifi', 'cffi', 'cfgv', 'cfn-lint', 'channels', 'chardet',
    'charset-normalizer', 'checkdigit', 'checkov', 'chevron', 'chromadb', 'circuitbreaker',
    'ciso8601', 'ckzg', 'clarabel', 'claude-agent-sdk', 'cleo', 'click', 'click-default-group',
    'click-didyoumean', 'click-option-group', 'click-plugins', 'click-repl',
    'clickhouse-connect', 'clickhouse-driver', 'cligj', 'cloud-sql-python-connector',
    'cloudevents', 'cloudflare', 'cloudpathlib', 'cloudpickle', 'cmake', 'cmdstanpy', 'cobble',
    'codeowners', 'codespell', 'cohere', 'colorama', 'colorclass', 'coloredlogs', 'colorful',
    'colorlog', 'comm', 'compressed-rtf', 'compressed-tensors', 'confection', 'configargparse',
    'configobj', 'configparser', 'confluent-kafka', 'connexion', 'constantly', 'construct',
    'constructs', 'contextlib2', 'contourpy', 'cookiecutter', 'coolname', 'courlan', 'coverage',
    'cramjam', 'crashtest', 'crc32c', 'crcmod', 'crewai', 'crewai-tools', 'cron-descriptor',
    'croniter', 'cronsim', 'cryptography', 'cssselect', 'cssselect2', 'cssutils', 'ctranslate2',
    'cuda-bindings', 'cuda-core', 'cuda-pathfinder', 'cuda-python', 'cuda-toolkit', 'curl-cffi',
    'curlify', 'cvxpy', 'cycler', 'cyclonedx-python-lib', 'cyclopts', 'cymem', 'cython',
    'cytoolz', 'dacite', 'daff', 'daft', 'dagster', 'dagster-aws', 'dagster-graphql',
    'dagster-pipes', 'dagster-postgres', 'dagster-shared', 'dagster-webserver', 'daphne',
    'dash', 'dask', 'dask-expr', 'databricks-agents', 'databricks-cli', 'databricks-connect',
    'databricks-labs-blueprint', 'databricks-labs-dqx', 'databricks-labs-lsql',
    'databricks-sdk', 'databricks-sql-connector', 'databricks-sqlalchemy', 'dataclasses',
    'dataclasses-json', 'datadog', 'datadog-api-client', 'datamodel-code-generator',
    'dataproperty', 'datasets', 'datasketch', 'dateparser', 'datetime', 'daytona',
    'daytona-analytics-api-client', 'daytona-analytics-api-client-async', 'daytona-api-client',
    'daytona-api-client-async', 'daytona-toolbox-api-client',
    'daytona-toolbox-api-client-async', 'db-dtypes', 'dbt-adapters', 'dbt-bigquery',
    'dbt-common', 'dbt-core', 'dbt-databricks', 'dbt-extractor', 'dbt-postgres', 'dbt-protos',
    'dbt-semantic-interfaces', 'dbt-snowflake', 'dbt-spark', 'ddgs', 'ddtrace', 'debugpy',
    'decorator', 'deepagents', 'deepdiff', 'deepmerge', 'defusedxml', 'delta-spark',
    'deltalake', 'dep-logic', 'dependency-groups', 'dependency-injector', 'deprecated',
    'deprecation', 'deptry', 'detect-installer', 'detect-secrets', 'diagrams', 'dictdiffer',
    'diff-cover', 'diffusers', 'dill', 'dirhash', 'dirtyjson', 'discord-py', 'diskcache',
    'disposable-email-domains', 'distlib', 'distributed', 'distro', 'dj-database-url', 'django',
    'django-celery-beat', 'django-cors-headers', 'django-debug-toolbar', 'django-environ',
    'django-extensions', 'django-filter', 'django-ipware', 'django-phonenumber-field',
    'django-redis', 'django-storages', 'django-stubs', 'django-stubs-ext',
    'django-timezone-field', 'djangorestframework', 'djangorestframework-simplejwt',
    'djangorestframework-stubs', 'dlt', 'dnspython', 'docker', 'docker-pycreds',
    'dockerfile-parse', 'docling', 'docling-core', 'docopt', 'docstring-parser', 'docutils',
    'dotenv', 'dpath', 'drf-spectacular', 'dspy', 'duckdb', 'dulwich', 'dunamai', 'durationpy',
    'dynaconf', 'e2b', 'easygui', 'ebcdic', 'ecdsa', 'edge-tts', 'editables', 'editorconfig',
    'einops', 'elastic-transport', 'elasticsearch', 'elasticsearch-dsl', 'elementpath',
    'elevenlabs', 'email-validator', 'emoji', 'entrypoints', 'enum-compat', 'enum34', 'envier',
    'environs', 'et-xmlfile', 'eth-abi', 'eth-account', 'eth-hash', 'eth-keyfile', 'eth-keys',
    'eth-rlp', 'eth-typing', 'eth-utils', 'etils', 'eval-type-backport', 'eventlet', 'events',
    'exa-py', 'exceptiongroup', 'exchange-calendars', 'execnet', 'executing', 'expiringdict',
    'expression', 'extract-msg', 'fabric', 'face', 'facebook-business', 'factory-boy',
    'faiss-cpu', 'fake-useragent', 'faker', 'fakeredis', 'fastapi', 'fastapi-cli',
    'fastapi-cloud-cli', 'fastapi-mcp', 'fastapi-sso', 'fastar', 'fastavro', 'fastcore',
    'fastembed', 'fasteners', 'faster-whisper', 'fastf1', 'fastjsonschema', 'fastmcp',
    'fastmcp-slim', 'fastparquet', 'fastspec', 'fasttransport', 'fastuuid', 'feedparser',
    'feedparser-sgmllib', 'fetch-use', 'ffmpeg-python', 'filelock', 'filetype', 'findpython',
    'fiona', 'fire', 'firebase-admin', 'firecrawl-anydoc', 'firecrawl-py', 'flake8', 'flask',
    'flask-appbuilder', 'flask-babel', 'flask-caching', 'flask-cors', 'flask-jwt-extended',
    'flask-limiter', 'flask-login', 'flask-session', 'flask-sqlalchemy', 'flask-wtf',
    'flatbuffers', 'flexcache', 'flexparser', 'flit', 'flit-core', 'flower', 'fonttools',
    'fpdf2', 'fqdn', 'freezegun', 'frozendict', 'frozenlist', 'fsspec', 'ftfy', 'func-timeout',
    'functions-framework', 'funcy', 'furl', 'future', 'fuzzywuzzy', 'gast', 'gcloud-aio-auth',
    'gcloud-aio-bigquery', 'gcloud-aio-storage', 'gcsfs', 'genai-prices', 'genson',
    'geographiclib', 'geoip2', 'geomet', 'geopandas', 'geopy', 'gepa', 'gevent',
    'geventhttpclient', 'gguf', 'ghapi', 'ghp-import', 'gitdb', 'github3-py', 'gitpython',
    'giturlparse', 'glom', 'google', 'google-adk', 'google-ads', 'google-ai-generativelanguage',
    'google-analytics-admin', 'google-analytics-data', 'google-api-core',
    'google-api-python-client', 'google-auth', 'google-auth-httplib2', 'google-auth-oauthlib',
    'google-cloud-aiplatform', 'google-cloud-alloydb', 'google-cloud-appengine-logging',
    'google-cloud-audit-log', 'google-cloud-automl', 'google-cloud-batch',
    'google-cloud-bigquery', 'google-cloud-bigquery-datatransfer',
    'google-cloud-bigquery-storage', 'google-cloud-bigtable', 'google-cloud-build',
    'google-cloud-compute', 'google-cloud-container', 'google-cloud-core',
    'google-cloud-datacatalog', 'google-cloud-dataflow-client', 'google-cloud-dataform',
    'google-cloud-dataplex', 'google-cloud-dataproc', 'google-cloud-dataproc-metastore',
    'google-cloud-datastore', 'google-cloud-discoveryengine', 'google-cloud-dlp',
    'google-cloud-firestore', 'google-cloud-iam', 'google-cloud-kms', 'google-cloud-language',
    'google-cloud-logging', 'google-cloud-managedkafka', 'google-cloud-memcache',
    'google-cloud-monitoring', 'google-cloud-orchestration-airflow', 'google-cloud-os-login',
    'google-cloud-pubsub', 'google-cloud-redis', 'google-cloud-resource-manager',
    'google-cloud-run', 'google-cloud-secret-manager', 'google-cloud-spanner',
    'google-cloud-speech', 'google-cloud-storage', 'google-cloud-storage-control',
    'google-cloud-storage-transfer', 'google-cloud-tasks', 'google-cloud-texttospeech',
    'google-cloud-trace', 'google-cloud-translate', 'google-cloud-videointelligence',
    'google-cloud-vision', 'google-cloud-workflows', 'google-crc32c', 'google-genai',
    'google-generativeai', 'google-pasta', 'google-re2', 'google-resumable-media',
    'googleapis-common-protos', 'gprof2dot', 'gql', 'gradio', 'gradio-client', 'granian',
    'graphene', 'graphql-core', 'graphql-relay', 'graphviz', 'great-expectations', 'greenback',
    'greenlet', 'gremlinpython', 'griffe', 'griffecli', 'griffelib', 'grimp', 'groq',
    'grpc-google-iam-v1', 'grpc-interceptor', 'grpcio', 'grpcio-gcp', 'grpcio-health-checking',
    'grpcio-reflection', 'grpcio-status', 'grpcio-tools', 'grpclib', 'gspread', 'gunicorn',
    'gymnasium', 'h11', 'h2', 'h3', 'h5py', 'habluetooth', 'harbor', 'harbor-rewardkit',
    'hatch', 'hatch-fancy-pypi-readme', 'hatch-vcs', 'hatchling', 'hexbytes', 'hf-xet',
    'highspy', 'hiredis', 'holidays', 'hpack', 'html2text', 'html5lib', 'htmldate', 'httpcore',
    'httpcore2', 'httplib2', 'httptools', 'httpx', 'httpx-sse', 'httpx-ws', 'httpx2',
    'httpx2-jsfetch', 'huey', 'huggingface-hub', 'humanfriendly', 'humanize', 'hvac',
    'hydra-core', 'hypercorn', 'hyperframe', 'hyperlink', 'hypothesis', 'icalendar', 'icdiff',
    'id', 'identify', 'idna', 'ifaddr', 'ijson', 'imagehash', 'imageio', 'imageio-ffmpeg',
    'imagesize', 'imbalanced-learn', 'immutabledict', 'import-linter', 'importlib-metadata',
    'importlib-resources', 'impyla', 'incremental', 'inflate64', 'inflect', 'inflection',
    'influxdb-client', 'iniconfig', 'inputimeout', 'inquirerpy', 'inspect-ai', 'installer',
    'instructor', 'intervaltree', 'invoke', 'ipdb', 'ipykernel', 'ipython', 'ipython-genutils',
    'ipython-pygments-lexers', 'ipywidgets', 'iso8601', 'isodate', 'isoduration', 'isort',
    'itsdangerous', 'jaraco-classes', 'jaraco-context', 'jaraco-functools', 'jax', 'jaxlib',
    'jaydebeapi', 'jedi', 'jeepney', 'jellyfish', 'jinja2', 'jinja2-humanize-extension',
    'jinxed', 'jira', 'jiter', 'jmespath', 'joblib', 'joserfc', 'jpype1', 'jq', 'jsbeautifier',
    'jsii', 'json-repair', 'json-rpc', 'json5', 'jsonconversion', 'jsondiff', 'jsonlines',
    'jsonpatch', 'jsonpath-ng', 'jsonpath-python', 'jsonpickle', 'jsonpointer', 'jsonref',
    'jsonschema', 'jsonschema-path', 'jsonschema-rs', 'jsonschema-specifications', 'junit-xml',
    'junitparser', 'jupyter', 'jupyter-builder', 'jupyter-client', 'jupyter-console',
    'jupyter-core', 'jupyter-events', 'jupyter-lsp', 'jupyter-server',
    'jupyter-server-terminals', 'jupyterlab', 'jupyterlab-pygments', 'jupyterlab-server',
    'jupyterlab-widgets', 'justext', 'jwcrypto', 'kafka-python', 'kaitaistruct', 'kaleido',
    'keras', 'kestra', 'keyring', 'keyrings-google-artifactregistry-auth', 'kfp', 'kgb',
    'kiwisolver', 'knack', 'kombu', 'korean-lunar-calendar', 'kubernetes', 'kubernetes-asyncio',
    'lance-namespace', 'lance-namespace-urllib3-client', 'lancedb', 'langchain',
    'langchain-anthropic', 'langchain-aws', 'langchain-classic', 'langchain-community',
    'langchain-core', 'langchain-google-community', 'langchain-google-genai',
    'langchain-google-vertexai', 'langchain-mcp-adapters', 'langchain-openai',
    'langchain-protocol', 'langchain-text-splitters', 'langcodes', 'langdetect', 'langfuse',
    'langgraph', 'langgraph-api', 'langgraph-checkpoint', 'langgraph-checkpoint-postgres',
    'langgraph-prebuilt', 'langgraph-sdk', 'langsmith', 'lark', 'launchdarkly-eventsource',
    'launchdarkly-server-sdk', 'lazy-loader', 'lazy-object-proxy', 'ldap3', 'leather',
    'levenshtein', 'libclang', 'libcst', 'librosa', 'librt', 'libtmux', 'license-expression',
    'lightgbm', 'lightning', 'lightning-utilities', 'limits', 'line-bot-sdk', 'linkify-it-py',
    'litellm', 'litellm-enterprise', 'litellm-proxy-extras', 'livekit-agents',
    'livekit-protocol', 'llama-cloud', 'llama-cloud-services', 'llama-index',
    'llama-index-core', 'llama-index-embeddings-openai',
    'llama-index-indices-managed-llama-cloud', 'llama-index-instrumentation',
    'llama-index-llms-openai', 'llama-index-readers-llama-parse', 'llama-index-workflows',
    'llama-parse', 'llguidance', 'llvmlite', 'lmnr', 'lmnr-claude-code-proxy', 'locket',
    'lockfile', 'locust', 'logfire', 'logfire-api', 'loguru', 'looker-sdk', 'lru-dict', 'lupa',
    'lxml', 'lxml-html-clean', 'lz4', 'magika', 'makefun', 'mako', 'mammoth', 'mando', 'mangum',
    'markdown', 'markdown-it-py', 'markdown2', 'markdownify', 'markitdown', 'marko',
    'markupsafe', 'marshmallow', 'marshmallow-dataclass', 'marshmallow-enum',
    'marshmallow-oneofschema', 'marshmallow-sqlalchemy', 'mashumaro', 'matplotlib',
    'matplotlib-inline', 'maturin', 'maxminddb', 'mbstrdecoder', 'mccabe', 'mcp', 'mcp-types',
    'mdit-py-plugins', 'mdurl', 'memory-profiler', 'memray', 'mergedeep', 'meson',
    'meson-python', 'methodtools', 'metricflow', 'microsoft-kiota-abstractions',
    'microsoft-kiota-authentication-azure', 'microsoft-kiota-http',
    'microsoft-kiota-serialization-form', 'microsoft-kiota-serialization-json',
    'microsoft-kiota-serialization-multipart', 'microsoft-kiota-serialization-text',
    'mini-swe-agent', 'minio', 'mistral-common', 'mistral-vibe', 'mistralai', 'mistune',
    'mitmproxy', 'mitmproxy-rs', 'mixpanel', 'mkdocs', 'mkdocs-autorefs', 'mkdocs-get-deps',
    'mkdocs-material', 'mkdocs-material-extensions', 'mkdocstrings', 'mkdocstrings-python',
    'ml-dtypes', 'mlflow', 'mlflow-skinny', 'mlflow-tracing', 'mmh3', 'mock', 'modal',
    'modelscope', 'mongomock', 'monotonic', 'more-itertools', 'moto', 'motor', 'moviepy',
    'mpmath', 'msal', 'msal-extensions', 'msgpack', 'msgraph-core', 'msgraph-sdk', 'msgspec',
    'msoffcrypto-tool', 'msrest', 'msrestazure', 'multidict', 'multiprocess', 'multitasking',
    'multivolumefile', 'murmurhash', 'mutagen', 'mypy', 'mypy-boto3-cloudformation',
    'mypy-boto3-dynamodb', 'mypy-boto3-ec2', 'mypy-boto3-glue', 'mypy-boto3-lambda',
    'mypy-boto3-rds', 'mypy-boto3-s3', 'mypy-boto3-secretsmanager', 'mypy-boto3-sqs',
    'mypy-boto3-sts', 'mypy-extensions', 'mypy-protobuf', 'mysql-connector-python',
    'mysqlclient', 'myst-parser', 'namex', 'nanoid', 'narwhals', 'natsort', 'nbclient',
    'nbconvert', 'nbformat', 'ndg-httpsclient', 'nemo-relay', 'neo4j', 'nest-asyncio',
    'nest-asyncio2', 'netaddr', 'networkx', 'nexus-rpc', 'nh3', 'ninja', 'nltk', 'nodeenv',
    'nodejs-wheel-binaries', 'nose', 'notebook', 'notebook-shim', 'nox', 'num2words', 'numba',
    'numcodecs', 'numexpr', 'numpy', 'numpy-financial', 'nvidia-cublas', 'nvidia-cublas-cu12',
    'nvidia-cuda-cupti', 'nvidia-cuda-cupti-cu12', 'nvidia-cuda-nvrtc',
    'nvidia-cuda-nvrtc-cu12', 'nvidia-cuda-runtime', 'nvidia-cuda-runtime-cu12',
    'nvidia-cudnn-cu12', 'nvidia-cudnn-cu13', 'nvidia-cufft', 'nvidia-cufft-cu12',
    'nvidia-cufile', 'nvidia-cufile-cu12', 'nvidia-curand', 'nvidia-curand-cu12',
    'nvidia-cusolver', 'nvidia-cusolver-cu12', 'nvidia-cusparse', 'nvidia-cusparse-cu12',
    'nvidia-cusparselt-cu12', 'nvidia-cusparselt-cu13', 'nvidia-cutlass-dsl',
    'nvidia-cutlass-dsl-libs-base', 'nvidia-ml-py', 'nvidia-nccl-cu12', 'nvidia-nccl-cu13',
    'nvidia-nvjitlink', 'nvidia-nvjitlink-cu12', 'nvidia-nvshmem-cu12', 'nvidia-nvshmem-cu13',
    'nvidia-nvtx', 'nvidia-nvtx-cu12', 'oauth2client', 'oauthlib', 'obstore', 'oci',
    'office365-rest-python-client', 'oldest-supported-numpy', 'olefile', 'oletools', 'ollama',
    'omegaconf', 'onnx', 'onnxruntime', 'openai', 'openai-agents', 'openai-harmony',
    'openapi-pydantic', 'openapi-schema-validator', 'openapi-spec-validator', 'opencensus',
    'opencensus-context', 'opencensus-ext-azure', 'opencv-contrib-python', 'opencv-python',
    'opencv-python-headless', 'openhands-sdk', 'openhands-tools',
    'openinference-instrumentation', 'openinference-semantic-conventions',
    'openlineage-integration-common', 'openlineage-python', 'openlineage-sql', 'openpyxl',
    'opensearch-protobufs', 'opensearch-py', 'opentelemetry-api', 'opentelemetry-distro',
    'opentelemetry-exporter-gcp-logging', 'opentelemetry-exporter-gcp-monitoring',
    'opentelemetry-exporter-gcp-trace', 'opentelemetry-exporter-otlp',
    'opentelemetry-exporter-otlp-proto-common', 'opentelemetry-exporter-otlp-proto-grpc',
    'opentelemetry-exporter-otlp-proto-http', 'opentelemetry-exporter-prometheus',
    'opentelemetry-instrumentation', 'opentelemetry-instrumentation-aiohttp-client',
    'opentelemetry-instrumentation-asgi', 'opentelemetry-instrumentation-asyncio',
    'opentelemetry-instrumentation-asyncpg', 'opentelemetry-instrumentation-boto3sqs',
    'opentelemetry-instrumentation-botocore', 'opentelemetry-instrumentation-celery',
    'opentelemetry-instrumentation-dbapi', 'opentelemetry-instrumentation-django',
    'opentelemetry-instrumentation-fastapi', 'opentelemetry-instrumentation-flask',
    'opentelemetry-instrumentation-google-genai', 'opentelemetry-instrumentation-grpc',
    'opentelemetry-instrumentation-httpx', 'opentelemetry-instrumentation-kafka-python',
    'opentelemetry-instrumentation-logging', 'opentelemetry-instrumentation-psycopg',
    'opentelemetry-instrumentation-psycopg2', 'opentelemetry-instrumentation-pymongo',
    'opentelemetry-instrumentation-redis', 'opentelemetry-instrumentation-requests',
    'opentelemetry-instrumentation-sqlalchemy', 'opentelemetry-instrumentation-sqlite3',
    'opentelemetry-instrumentation-starlette', 'opentelemetry-instrumentation-system-metrics',
    'opentelemetry-instrumentation-threading', 'opentelemetry-instrumentation-urllib',
    'opentelemetry-instrumentation-urllib3', 'opentelemetry-instrumentation-wsgi',
    'opentelemetry-propagator-aws-xray', 'opentelemetry-proto',
    'opentelemetry-resource-detector-azure', 'opentelemetry-resourcedetector-gcp',
    'opentelemetry-sdk', 'opentelemetry-sdk-extension-aws',
    'opentelemetry-semantic-conventions', 'opentelemetry-semantic-conventions-ai',
    'opentelemetry-util-genai', 'opentelemetry-util-http', 'opt-einsum', 'optree', 'optuna',
    'oracledb', 'orbax-checkpoint', 'ordered-set', 'orderedmultidict', 'orderly-set', 'orjson',
    'ormsgpack', 'ortools', 'oscrypto', 'osqp', 'oss2', 'outcome', 'overrides',
    'packageurl-python', 'packaging', 'paginate', 'paho-mqtt', 'pamqp', 'pandas', 'pandas-gbq',
    'pandas-stubs', 'pandera', 'pandocfilters', 'papermill', 'parameterized', 'paramiko',
    'parse', 'parse-type', 'parsedatetime', 'parsimonious', 'parso', 'partd',
    'partial-json-parser', 'parver', 'passlib', 'pastel', 'patchelf', 'pathable', 'pathlib',
    'pathlib-abc', 'pathos', 'pathspec', 'pathvalidate', 'patsy', 'pbr', 'pbs-installer',
    'pcodedmp', 'pdbr', 'pdf2image', 'pdfminer-six', 'pdfplumber', 'pdm', 'peewee', 'pefile',
    'peft', 'pendulum', 'pep517', 'pex', 'pexpect', 'pfzy', 'pg8000', 'pglast', 'pgpy',
    'pgvector', 'phonenumbers', 'pi-heif', 'pickleshare', 'pika', 'pikepdf', 'pillow',
    'pillow-heif', 'pinecone', 'pinotdb', 'pint', 'pip', 'pip-api', 'pip-audit',
    'pip-requirements-parser', 'pip-tools', 'pipdeptree', 'pipenv', 'pipx', 'pkgconfig',
    'pkginfo', 'pkgutil-resolve-name', 'platformdirs', 'playwright', 'plotly', 'pluggy',
    'plumbum', 'ply', 'poethepoet', 'poetry', 'poetry-core', 'poetry-plugin-export', 'polars',
    'polars-runtime-32', 'polib', 'polyfactory', 'pooch', 'port-for', 'portalocker',
    'postgrest', 'posthog', 'pox', 'ppft', 'pprintpp', 'prance', 'pre-commit', 'prefect',
    'prefect-aws', 'prek', 'preshed', 'presidio-analyzer', 'prettytable', 'primp', 'priority',
    'prison', 'probableparsing', 'proglog', 'progressbar2', 'prometheus-client',
    'prometheus-fastapi-instrumentator', 'prompt-toolkit', 'propcache', 'prophet', 'protego',
    'proto-plus', 'protobuf', 'protobuf3-to-dict', 'psutil', 'psycopg', 'psycopg-binary',
    'psycopg-pool', 'psycopg2', 'psycopg2-binary', 'ptyprocess', 'publication', 'publicsuffix2',
    'pulp', 'pulumi', 'pulumi-aws', 'pure-eval', 'pure-sasl', 'puremagic', 'py', 'py-cpuinfo',
    'py-key-value-aio', 'py-key-value-shared', 'py-partiql-parser', 'py-serializable', 'py-spy',
    'py-vapid', 'py4j', 'py7zr', 'pyahocorasick', 'pyaml', 'pyarrow', 'pyarrow-hotfix',
    'pyasn1', 'pyasn1-modules', 'pyathena', 'pybase64', 'pybcj', 'pybind11', 'pybreaker',
    'pycares', 'pycarlo', 'pyclipper', 'pycodestyle', 'pycomposefile', 'pycountry', 'pycparser',
    'pycrypto', 'pycryptodome', 'pycryptodomex', 'pydantic', 'pydantic-ai', 'pydantic-ai-slim',
    'pydantic-core', 'pydantic-evals', 'pydantic-extra-types', 'pydantic-graph',
    'pydantic-settings', 'pydash', 'pydata-google-auth', 'pydeck', 'pydeequ', 'pydocket',
    'pydot', 'pydub', 'pydyf', 'pyee', 'pyelftools', 'pyfiglet', 'pyflakes', 'pygit2',
    'pygithub', 'pygments', 'pygtrie', 'pyhanko', 'pyhanko-certvalidator', 'pyhcl', 'pyhive',
    'pyhumps', 'pyiceberg', 'pyiceberg-core', 'pyinstaller', 'pyinstaller-hooks-contrib',
    'pyinstrument', 'pyjwt', 'pylatexenc', 'pylint', 'pylsqpack', 'pyluach',
    'pymdown-extensions', 'pymilvus', 'pymongo', 'pympler', 'pymssql', 'pymsteams', 'pymupdf',
    'pymupdf-layout', 'pymupdf4llm', 'pymysql', 'pynacl', 'pynndescent', 'pyodbc', 'pyogrio',
    'pyopengl', 'pyopenssl', 'pyotp', 'pypandoc', 'pyparsing', 'pypdf', 'pypdf2', 'pypdfium2',
    'pyperclip', 'pyphen', 'pypika', 'pypng', 'pyppmd', 'pyproj', 'pyproject-api',
    'pyproject-hooks', 'pyproject-metadata', 'pyrate-limiter', 'pyreadline3', 'pyrefly',
    'pyrfc3339', 'pyright', 'pyroaring', 'pyroscope-io', 'pyrsistent', 'pyserial', 'pysftp',
    'pysocks', 'pyspark', 'pyspnego', 'pytablewriter', 'pytesseract', 'pytest',
    'pytest-aiohttp', 'pytest-asyncio', 'pytest-base-url', 'pytest-benchmark', 'pytest-cov',
    'pytest-custom-exit-code', 'pytest-django', 'pytest-env', 'pytest-forked',
    'pytest-homeassistant-custom-component', 'pytest-html', 'pytest-httpx', 'pytest-icdiff',
    'pytest-json-ctrf', 'pytest-json-report', 'pytest-metadata', 'pytest-mock', 'pytest-order',
    'pytest-playwright', 'pytest-postgresql', 'pytest-randomly', 'pytest-repeat',
    'pytest-rerunfailures', 'pytest-runner', 'pytest-socket', 'pytest-split', 'pytest-sugar',
    'pytest-timeout', 'pytest-unordered', 'pytest-xdist', 'python-bidi', 'python-box',
    'python-calamine', 'python-crfsuite', 'python-crontab', 'python-daemon', 'python-dateutil',
    'python-decouple', 'python-discovery', 'python-docx', 'python-dotenv', 'python-engineio',
    'python-frontmatter', 'python-gitlab', 'python-gnupg', 'python-hcl2', 'python-http-client',
    'python-jenkins', 'python-jose', 'python-json-logger', 'python-keycloak',
    'python-levenshtein', 'python-magic', 'python-multipart', 'python-on-whales', 'python-pptx',
    'python-slugify', 'python-snappy', 'python-socketio', 'python-socks', 'python-stdnum',
    'python-tds', 'python-telegram-bot', 'python-ulid', 'python-utils', 'python3-openid',
    'python3-saml', 'pytimeparse', 'pytokens', 'pytorch-lightning', 'pytz', 'pytzdata',
    'pyvespa', 'pywavelets', 'pywebpush', 'pywin32', 'pywin32-ctypes', 'pyxlsb', 'pyyaml',
    'pyyaml-env-tag', 'pyyaml-ft', 'pyzipper', 'pyzmq', 'pyzstd', 'qdrant-client', 'qrcode',
    'quack-kernels', 'questionary', 'radon', 'rank-bm25', 'rapidfuzz', 'rasterio', 'ratelimit',
    'ray', 'rdflib', 'reactivex', 'readchar', 'readme-renderer', 'realtime', 'redis',
    'redshift-connector', 'referencing', 'regex', 'reportlab', 'requests', 'requests-aws4auth',
    'requests-cache', 'requests-file', 'requests-mock', 'requests-ntlm', 'requests-oauthlib',
    'requests-toolbelt', 'requirements-parser', 'resend', 'resolvelib', 'responses', 'respx',
    'restrictedpython', 'restructuredtext-lint', 'retry', 'retrying', 'rfc3339-validator',
    'rfc3986', 'rfc3986-validator', 'rfc3987-syntax', 'rich', 'rich-argparse', 'rich-click',
    'rich-rst', 'rich-toolkit', 'rignore', 'rlp', 'roman-numerals', 'rouge-score', 'rpds-py',
    'rq', 'rsa', 'rtfde', 'rtree', 'ruamel-yaml', 'ruamel-yaml-clib', 'ruff', 'rustworkx',
    's3fs', 's3transfer', 'safehttpx', 'safetensors', 'sagemaker', 'sagemaker-core',
    'sagemaker-studio', 'scantree', 'schedule', 'schema', 'schemathesis', 'scikit-build-core',
    'scikit-image', 'scikit-learn', 'scipy', 'scp', 'scramp', 'screeninfo', 'scs', 'seaborn',
    'secretstorage', 'segment-analytics-python', 'selectolax', 'selenium', 'semantic-version',
    'semgrep', 'semver', 'send2trash', 'sendgrid', 'sentence-transformers', 'sentencepiece',
    'sentinels', 'sentry-sdk', 'service-identity', 'setproctitle', 'setuptools',
    'setuptools-rust', 'setuptools-scm', 'sglang', 'sgmllib3k', 'sh', 'shap', 'shapely',
    'shellingham', 'shortuuid', 'simple-gcp-object-downloader', 'simple-salesforce',
    'simple-websocket', 'simpleeval', 'simplejson', 'singer-sdk', 'six', 'skops', 'slack-bolt',
    'slack-sdk', 'slackclient', 'slicer', 'slowapi', 'smart-open', 'smbprotocol',
    'smdebug-rulesconfig', 'smmap', 'sniffio', 'snowballstemmer', 'snowflake-connector-python',
    'snowflake-core', 'snowflake-snowpark-python', 'snowflake-sqlalchemy', 'snowplow-tracker',
    'social-auth-app-django', 'social-auth-core', 'socksio', 'sortedcontainers', 'sounddevice',
    'soundfile', 'soupsieve', 'soxr', 'spacy', 'spacy-legacy', 'spacy-loggers', 'sparklines',
    'speechrecognition', 'sphinx', 'sphinx-autodoc-typehints', 'sphinx-copybutton',
    'sphinx-design', 'sphinx-rtd-theme', 'sphinxcontrib-applehelp', 'sphinxcontrib-devhelp',
    'sphinxcontrib-htmlhelp', 'sphinxcontrib-jquery', 'sphinxcontrib-jsmath',
    'sphinxcontrib-mermaid', 'sphinxcontrib-qthelp', 'sphinxcontrib-serializinghtml',
    'sql-metadata', 'sqlalchemy', 'sqlalchemy-bigquery', 'sqlalchemy-spanner',
    'sqlalchemy-utils', 'sqlfluff', 'sqlglot', 'sqlite-vec', 'sqlmodel', 'sqlparams',
    'sqlparse', 'srsly', 'sse-starlette', 'sseclient-py', 'sshtunnel', 'stack-data', 'stamina',
    'stanio', 'starkbank-ecdsa', 'starlette', 'statsd', 'statsmodels', 'std-uritemplate',
    'stevedore', 'storage3', 'strands-agents', 'strawberry-graphql', 'streamlit', 'strenum',
    'strictyaml', 'stringcase', 'stripe', 'striprtf', 'structlog', 'subprocess-tee', 'supabase',
    'supabase-auth', 'supabase-functions', 'supervisor', 'svcs', 'svglib', 'svix', 'swebench',
    'swesmith', 'swifter', 'sympy', 'synchronicity', 'syrupy', 'tableauserverclient',
    'tabledata', 'tabulate', 'tavily-python', 'tblib', 'temporalio', 'tenacity', 'tensorboard',
    'tensorboard-data-server', 'tensorflow', 'tensorflow-estimator',
    'tensorflow-io-gcs-filesystem', 'teradatasql', 'termcolor', 'terminado', 'terminaltables',
    'testcontainers', 'text-unidecode', 'texttable', 'textual', 'textual-speedups', 'thefuzz',
    'thinc', 'threadpoolctl', 'thrift', 'thrift-sasl', 'tifffile', 'tiktoken', 'time-machine',
    'timezonefinder', 'timm', 'tinycss2', 'tinyhtml5', 'tld', 'tldextract', 'tokenize-rt',
    'tokenizers', 'tom-swe', 'toml', 'tomli', 'tomli-w', 'tomlkit', 'toolz', 'toons',
    'toposort', 'torch', 'torchaudio', 'torchmetrics', 'torchvision', 'tornado', 'tox',
    'tox-uv', 'tqdm', 'trafilatura', 'traitlets', 'transformers', 'tree-sitter',
    'tree-sitter-bash', 'tree-sitter-c', 'tree-sitter-c-sharp', 'tree-sitter-embedded-template',
    'tree-sitter-go', 'tree-sitter-java', 'tree-sitter-javascript', 'tree-sitter-language-pack',
    'tree-sitter-languages', 'tree-sitter-php', 'tree-sitter-python', 'tree-sitter-ruby',
    'tree-sitter-rust', 'tree-sitter-typescript', 'tree-sitter-yaml', 'trimesh', 'trino',
    'trio', 'trio-websocket', 'triton', 'tritonclient', 'trove-classifiers', 'truststore',
    'twilio', 'twine', 'twisted', 'txaio', 'ty', 'typedload', 'typeguard', 'typepy', 'typer',
    'typer-slim', 'types-aioboto3', 'types-aiobotocore', 'types-aiobotocore-s3',
    'types-aiofiles', 'types-awscrt', 'types-boto3', 'types-boto3-s3', 'types-cachetools',
    'types-certifi', 'types-cffi', 'types-croniter', 'types-deprecated', 'types-docutils',
    'types-html5lib', 'types-jsonschema', 'types-markdown', 'types-openpyxl', 'types-paramiko',
    'types-protobuf', 'types-psutil', 'types-psycopg2', 'types-pymysql', 'types-pyopenssl',
    'types-python-dateutil', 'types-python-slugify', 'types-pytz', 'types-pyyaml',
    'types-redis', 'types-requests', 'types-retry', 'types-s3transfer', 'types-setuptools',
    'types-tabulate', 'types-toml', 'types-tqdm', 'types-urllib3', 'types-webencodings',
    'typing-extensions', 'typing-inspect', 'typing-inspection', 'tyro', 'tzdata', 'tzlocal',
    'ua-parser', 'ua-parser-builtins', 'uamqp', 'uc-micro-py', 'ujson', 'ultralytics',
    'ultralytics-thop', 'umap-learn', 'uncalled-for', 'unearth', 'unicodecsv', 'unidecode',
    'unidiff', 'unittest-xml-reporting', 'universal-pathlib', 'unstructured-client',
    'uri-template', 'uritemplate', 'uritools', 'url-normalize', 'urllib3', 'urwid', 'usaddress',
    'user-agents', 'userpath', 'uuid-utils', 'uuid6', 'uuid7', 'uv', 'uv-build',
    'uv-dynamic-versioning', 'uvicorn', 'uvicorn-worker', 'uvloop', 'validators', 'vcrpy',
    'vcs-versioning', 'vine', 'virtualenv', 'voluptuous', 'vulture', 'w3lib', 'waitress',
    'wandb', 'wasabi', 'watchdog', 'watchfiles', 'watchtower', 'wcmatch', 'wcwidth', 'weasel',
    'weasyprint', 'weaviate-client', 'web3', 'webauthn', 'webcolors', 'webdriver-manager',
    'webencodings', 'webob', 'websocket-client', 'websockets', 'werkzeug', 'wheel', 'whenever',
    'whitenoise', 'widgetsnbextension', 'wikipedia-api', 'wirerope', 'workos', 'wrapt',
    'wsproto', 'wtforms', 'xarray', 'xattr', 'xgboost', 'xgrammar', 'xlrd', 'xlsxwriter',
    'xlwt', 'xmlschema', 'xmlsec', 'xmltodict', 'xxhash', 'xyzservices', 'yamllint',
    'yandexcloud', 'yapf', 'yarl', 'ydb', 'yfinance', 'youtube-transcript-api', 'yt-dlp',
    'z3-solver', 'zarr', 'zeep', 'zipp', 'zope-event', 'zope-interface', 'zopfli', 'zstandard',
    'zstd', 'zxcvbn',
])

# 2000 most-downloaded npm packages (last month)
TOP_NPM = frozenset([
    '7zip-bin', 'abortcontroller-polyfill', 'abs-svg-path', 'abstract-logging', 'acorn',
    'acorn-jsx', 'acorn-loose', 'add-dom-event-listener', 'add-stream',
    'adjust-sourcemap-loader', 'adm-zip', 'ag-charts-locale', 'ag-grid-community',
    'ag-grid-enterprise', 'ag-grid-react', 'aggregate-error', 'ajv', 'ajv-draft-04',
    'ajv-formats', 'ajv-keywords', 'align-text', 'angular', 'angular-eslint',
    'angular-html-parser', 'another-json', 'ansi-colors', 'ansi-cyan', 'ansi-gray', 'ansi-html',
    'ansi-html-community', 'ansi-red', 'ansi-regex', 'ansi-to-html', 'ansis', 'antlr4',
    'any-observable', 'any-promise', 'apache-arrow', 'apexcharts', 'apg-lite', 'apollo-link',
    'apollo-link-http', 'apollo-link-http-common', 'app-root-path', 'appdirsjs', 'arg',
    'argparse', 'arr-diff', 'arr-flatten', 'array-back', 'array-differ', 'array-each',
    'array-filter', 'array-find', 'array-find-index', 'array-ify', 'array-includes',
    'array-initial', 'array-iterate', 'array-last', 'array-parallel', 'array-series',
    'array-slice', 'array-sort', 'array-timsort', 'array-tree-filter', 'array-union',
    'array-uniq', 'array-unique', 'array.prototype.filter', 'array.prototype.find',
    'array.prototype.findlast', 'array.prototype.findlastindex', 'array.prototype.flat',
    'array.prototype.flatmap', 'array.prototype.map', 'array.prototype.reduce',
    'array.prototype.toreversed', 'array.prototype.tosorted', 'arraybuffer.prototype.slice',
    'arrify', 'as-array', 'asap', 'assertion-error', 'ast-types-flow', 'async-limiter',
    'async-listener', 'async-validator', 'atomic-sleep', 'autoprefixer',
    'available-typed-arrays', 'aws-jwt-verify', 'axios', 'axios-mock-adapter', 'axios-ntlm',
    'axios-proxy-builder', 'axios-retry', 'azure-devops-node-api', 'babel-helper-regex',
    'babel-loader', 'babel-plugin-jsx-dom-expressions', 'babel-plugin-syntax-hermes-parser',
    'babel-plugin-syntax-object-rest-spread', 'babel-plugin-transform-es2015-object-super',
    'babel-plugin-transform-es2015-sticky-regex', 'babel-plugin-transform-es2015-unicode-regex',
    'babel-plugin-transform-object-rest-spread', 'babel-preset-current-node-syntax',
    'babel-preset-env', 'babel-preset-expo', 'babel-preset-fbjs', 'babel-preset-jest',
    'babel-preset-react-app', 'babel-preset-solid', 'babel-runtime', 'babel-types', 'babylon',
    'bail', 'bare-events', 'bare-path', 'bare-url', 'base64-stream', 'basic-auth', 'batch',
    'bcp-47', 'bcrypt', 'before-after-hook', 'better-ajv-errors', 'bfj', 'bin-build',
    'binary-extensions', 'bits-ui', 'block-stream', 'bn.js', 'body-parser', 'bole', 'bootstrap',
    'bplist-parser', 'broccoli-persistent-filter', 'brorand', 'browser-image-compression',
    'browser-process-hrtime', 'browserslist', 'bs-logger', 'bson', 'buffer-equal-constant-time',
    'buffer-image-size', 'buffer-indexof-polyfill', 'builtin-status-codes', 'bullmq', 'busboy',
    'byline', 'byte-counter', 'bytes', 'bytewise-core', 'c12', 'cacache', 'cache-base',
    'cache-content-type', 'cache-manager', 'cacheable-request', 'caldate', 'call-me-maybe',
    'caller-path', 'camelcase-css', 'camelcase-keys', 'canonicalize', 'canvas',
    'canvas-color-tracker', 'canvaskit-wasm', 'canvg', 'case',
    'case-sensitive-paths-webpack-plugin', 'castable-video', 'cfb', 'chai', 'chalk',
    'chalk-template', 'chance', 'char-regex', 'char-spinner', 'character-entities-html4',
    'chart.js', 'chartjs-adapter-date-fns', 'chartjs-color', 'chartjs-color-string',
    'check-error', 'check-types', 'cheerio', 'cheerio-select', 'cheminfo-types', 'chmodrp',
    'chokidar', 'chroma-js', 'chrome-trace-event', 'chrono-node', 'classcat', 'classnames',
    'clean-css', 'clean-stack', 'clean-webpack-plugin', 'clear-module', 'cli', 'cli-cursor',
    'cli-progress', 'cli-table3', 'cli-truncate', 'clone-response', 'cloneable-readable',
    'clsx', 'cm6-theme-basic-light', 'collection-map', 'color', 'color-alpha', 'color-convert',
    'color-name', 'color-normalize', 'color-parse', 'color-rgba', 'color-space', 'color-string',
    'color-support', 'colord', 'colorette', 'colorjs.io', 'columnify', 'combined-stream',
    'comma-separated-tokens', 'command-line-args', 'commander', 'comment-json',
    'comment-parser', 'commitlint', 'common-path-prefix', 'compare-func', 'component-emitter',
    'compress-commons', 'concat-stream', 'concurrently', 'confbox', 'config',
    'console-log-level', 'console-table-printer', 'consolidated-events', 'constructs',
    'contains-path', 'content-disposition', 'content-security-policy-parser', 'content-type',
    'continuable-cache', 'conventional-changelog-angular', 'conventional-changelog-config-spec',
    'conventional-changelog-conventionalcommits', 'conventional-changelog-preset-loader',
    'conventional-commit-types', 'conventional-commits-parser', 'cookie', 'cookie-parser',
    'copy-descriptor', 'copy-text-to-clipboard', 'copy-webpack-plugin', 'core-js', 'cors',
    'cosmiconfig-typescript-loader', 'create-error', 'create-error-class',
    'create-react-context', 'create-require', 'crelt', 'cropperjs', 'cross-env', 'cross-fetch',
    'cross-spawn', 'cross-zip', 'crypto-random-string', 'crypto-randomuuid',
    'cspell-config-lib', 'css', 'css-background-parser', 'css-box-model', 'css-box-shadow',
    'css-color-keywords', 'css-color-names', 'css-declaration-sorter', 'css-font-size-keywords',
    'css-font-style-keywords', 'css-functions-list', 'css-gradient-parser', 'css-has-pseudo',
    'css-in-js-utils', 'css-line-break', 'css-loader', 'css-mediaquery',
    'css-minimizer-webpack-plugin', 'css-parse', 'css-prefers-color-scheme', 'css-select',
    'css-selector-parser', 'css-selector-tokenizer', 'css-shorthand-properties',
    'css-to-react-native', 'css-tokenize', 'css-tree', 'css-unit-converter', 'css-value',
    'css-vendor', 'css-what', 'css.escape', 'csscolorparser', 'cssfontparser', 'csso', 'cssom',
    'csstype', 'csv', 'csv-generate', 'csv-parse', 'csv-parser', 'csv-stringify', 'csv-writer',
    'csvtojson', 'cucumber-html-reporter', 'culori', 'currently-unhandled',
    'custom-media-element', 'cycle', 'cypress', 'cypress-file-upload',
    'cypress-multi-reporters', 'd3', 'd3-array', 'd3-color', 'd3-drag', 'd3-dsv', 'd3-fetch',
    'd3-format', 'd3-interpolate-path', 'd3-path', 'd3-random', 'd3-scale-chromatic',
    'd3-selection', 'd3-time', 'd3-time-format', 'd3-timer', 'd3-zoom', 'dash-video-element',
    'data-uri-to-buffer', 'datatables.net', 'date-arithmetic', 'date-fns', 'date-fns-jalali',
    'date-fns-tz', 'date-format', 'date-holidays-parser', 'dayjs', 'db0', 'dc-polyfill',
    'debounce-promise', 'debug', 'decache', 'decamelize-keys', 'decompress-response',
    'decompress-unzip', 'dedent', 'deep-extend', 'defer-to-connect', 'define-lazy-prop',
    'delay', 'delayed-stream', 'delegate', 'deprecated-react-native-prop-types', 'deprecation',
    'deps-sort', 'derive-valtio', 'destroy', 'detect-file', 'detect-newline', 'detective-sass',
    'detective-typescript', 'deterministic-object-hash', 'dfa', 'diff', 'diffable-html',
    'digest-fetch', 'doc-path', 'doctrine', 'doiuse', 'dom-align', 'dom-converter',
    'dom-helpers', 'dom-mutator', 'dom-serialize', 'dom-serializer', 'dom-walk',
    'domelementtype', 'domhandler', 'domutils', 'dotenv', 'dotenv-cli', 'dotenv-flow',
    'dotenv-webpack', 'double-ended-queue', 'drizzle-orm', 'duplexer', 'duplexify', 'duration',
    'easy-table', 'eazy-logger', 'ee-first', 'elegant-spinner', 'element-resize-detector',
    'elementtree', 'emittery', 'emoji-regex', 'encodeurl', 'encoding-sniffer', 'end-of-stream',
    'engine.io-client', 'engine.io-parser', 'entities', 'env-cmd', 'env-paths', 'env-string',
    'err-code', 'error', 'error-causes', 'error-ex', 'error-stack-parser-es', 'errorhandler',
    'es-aggregate-error', 'es-errors', 'es-iterator-helpers', 'es-object-atoms',
    'es-shim-unscopables', 'es6-error', 'es6-map', 'es6-object-assign', 'es6-set', 'es6-symbol',
    'es6-weak-map', 'esast-util-from-js', 'esbuild', 'esbuild-linux-64', 'esbuild-plugin-alias',
    'esbuild-wasm', 'escape-html', 'eslint', 'eslint-config-airbnb',
    'eslint-config-airbnb-base', 'eslint-config-airbnb-typescript', 'eslint-config-expo',
    'eslint-config-flat-gitignore', 'eslint-config-standard', 'eslint-config-turbo',
    'eslint-flat-config-utils', 'eslint-import-resolver-node',
    'eslint-import-resolver-typescript', 'eslint-plugin-compat', 'eslint-plugin-html',
    'eslint-plugin-jest-dom', 'eslint-plugin-json', 'eslint-plugin-mocha',
    'eslint-plugin-no-only-tests', 'eslint-plugin-react-dom', 'eslint-plugin-react-refresh',
    'eslint-plugin-svelte', 'eslint-plugin-yml', 'eslint-webpack-plugin', 'esniff', 'esrap',
    'essentials', 'etag', 'ev-emitter', 'event-emitter', 'event-source-polyfill',
    'event-target-polyfill', 'event-target-shim', 'eventemitter2', 'events', 'events-channel',
    'events-intercept', 'events-sync', 'eventsource-parser', 'exceljs', 'exec-async', 'exec-sh',
    'execa', 'execall', 'exegesis-express', 'exit-hook', 'exit-on-epipe', 'expand-template',
    'expo-build-properties', 'expo-dev-client', 'expo-eas-client', 'expo-file-system',
    'expo-image', 'expo-image-loader', 'expo-manifests', 'expo-router', 'expo-server',
    'expo-video', 'express', 'express-basic-auth', 'express-http-proxy', 'express-jwt',
    'express-prom-bundle', 'express-promise-router', 'express-rate-limit', 'express-session',
    'express-unless', 'express-validator', 'extend-shallow', 'extendable-error',
    'extension-port-stream', 'extract-zip', 'extrareqp2', 'fabric', 'fake-indexeddb', 'faker',
    'fancy-canvas', 'fancy-log', 'fast-content-type-parse', 'fast-copy', 'fast-csv',
    'fast-diff', 'fast-json-parse', 'fast-json-patch', 'fast-json-stable-stringify',
    'fast-json-stringify', 'fast-jwt', 'fast-png', 'fast-redact', 'fast-shallow-equal',
    'fast-string-truncated-width', 'fast-string-width', 'fast-text-encoding', 'fast-url-parser',
    'fast-xml-builder', 'fast-xml-parser', 'fastify-plugin', 'fastq', 'fecha', 'fetch-blob',
    'fetch-cookie', 'fetch-mock', 'fetch-nodeshim', 'fetch-retry', 'file-entry-cache',
    'file-loader', 'file-selector', 'file-stream-rotator', 'file-system-cache', 'file-type',
    'file-uri-to-path', 'file-url', 'filelist', 'filenamify', 'fill-range', 'filter-obj',
    'final-form', 'finalhandler', 'find-babel-config', 'find-cache-directory', 'find-file-up',
    'find-my-way', 'find-my-way-ts', 'find-process', 'find-replace', 'find-test-names',
    'first-chunk-stream', 'flat', 'flatqueue', 'flatted', 'flmngr', 'flow-enums-runtime',
    'flow-parser', 'flush-write-stream', 'focus-lock', 'focus-trap', 'follow-redirects',
    'force-graph', 'fork-ts-checker-webpack-plugin', 'form-data', 'form-data-encoder', 'format',
    'format-util', 'formidable', 'formik', 'forwarded', 'forwarded-parse', 'fragment-cache',
    'framer-motion', 'fresh', 'from', 'front-matter', 'fs-extra', 'fs-minipass', 'fs2',
    'ftp-response-parser', 'function.prototype.name', 'generate-object-property',
    'generic-names', 'get-intrinsic', 'get-npm-tarball-url', 'get-proto', 'get-proxy',
    'get-stdin', 'get-stream', 'get-them-args', 'get-tsconfig', 'get-uri', 'getopts',
    'git-config-path', 'git-log-parser', 'git-node-fs', 'git-remote-origin-url', 'git-up',
    'git-url-parse', 'github-from-package', 'glob', 'glob-parent', 'glob-promise',
    'global-agent', 'global-prefix', 'globalthis', 'globby', 'glsl-token-scope',
    'glsl-token-string', 'glsl-tokenizer', 'golden-fleece', 'google-logging-utils', 'got',
    'graceful-fs', 'gradient-string', 'graphiql', 'graphql', 'graphql-config',
    'graphql-depth-limit', 'graphql-http', 'graphql-language-service',
    'graphql-playground-html', 'graphql-query-complexity', 'graphql-request', 'graphql-scalars',
    'graphql-subscriptions', 'graphql-tag', 'graphql-tools', 'graphql-type-json', 'graphql-ws',
    'grouped-queue', 'grunt-legacy-log', 'grunt-legacy-log-utils', 'guess-json-indent',
    'guid-typescript', 'gulp-sort', 'gulplog', 'gzip-size', 'happy-dom', 'har-schema',
    'hard-rejection', 'harmony-reflect', 'has-ansi', 'hashery', 'hast-util-format',
    'hast-util-from-dom', 'hast-util-from-html', 'hast-util-from-html-isomorphic',
    'hast-util-to-html', 'hast-util-to-jsx-runtime', 'hast-util-to-text', 'he',
    'headers-polyfill', 'headers-utils', 'helmet', 'hermes-parser', 'hex-color-regex',
    'hex-rgb', 'hls-video-element', 'hmac-drbg', 'homedir-polyfill', 'hono-openapi',
    'hookified', 'hoopy', 'hsl-regex', 'hsla-regex', 'html-comment-regex', 'html-dom-parser',
    'html-element-map', 'html-encoding-sniffer', 'html-entities', 'html-loader',
    'html-minifier', 'html-minifier-terser', 'html-parse-stringify', 'html-react-parser',
    'html-tags', 'html-to-image', 'html-to-text', 'html-tokenize', 'html-url-attributes',
    'html-void-elements', 'html-webpack-plugin', 'html-whitespace-sensitive-tag-names',
    'htmlfy', 'htmlparser2', 'http-cache-semantics', 'http-call', 'http-cookie-agent',
    'http-deceiver', 'http-errors', 'http-link-header', 'http-parser-js', 'http-proxy',
    'http-proxy-agent', 'http-proxy-middleware', 'http-reasons', 'http-response-object',
    'http-server', 'http-shutdown', 'http-signature', 'http-status', 'http-status-codes',
    'http-terminator', 'https-proxy-agent', 'httpxy', 'human-signals', 'humanize-ms',
    'humanize-string', 'hyperdyperid', 'hyphen', 'i18next-fs-backend', 'identity-obj-proxy',
    'image-meta', 'image-q', 'image-size', 'image-ssim', 'immutable', 'import-fresh',
    'import-from', 'import-without-cache', 'indent-string', 'indexes-of', 'inflation',
    'ink-spinner', 'ink-table', 'ink-text-input', 'inline-style-parser', 'inquirer',
    'inquirer-autocomplete-prompt', 'install', 'intl', 'into-stream', 'ioredis', 'iota-array',
    'is-absolute', 'is-absolute-url', 'is-any-array', 'is-arrayish', 'is-binary-path',
    'is-buffer', 'is-color-stop', 'is-date-object', 'is-docker', 'is-dotfile', 'is-error',
    'is-extendable', 'is-extglob', 'is-html', 'is-in-ssh', 'is-inside-container', 'is-integer',
    'is-invalid-path', 'is-my-ip-valid', 'is-nan', 'is-natural-number', 'is-network-error',
    'is-number', 'is-number-like', 'is-number-object', 'is-obj', 'is-object', 'is-path-cwd',
    'is-path-in-cwd', 'is-path-inside', 'is-plain-obj', 'is-plain-object', 'is-promise',
    'is-regex', 'is-relative', 'is-stream', 'is-stream-ended', 'is-string', 'is-string-blank',
    'is-svg', 'is-text-path', 'is-typed-array', 'is-typedarray', 'is-unc-path', 'is-unsafe',
    'is-url', 'is-url-superb', 'is-valid-path', 'is-wsl', 'is-yarn-global', 'isarray',
    'isomorphic-fetch', 'isomorphic-unfetch', 'isstream', 'issue-parser', 'isurl', 'iterare',
    'iterator.prototype', 'jackspeak', 'javascript-natural-sort', 'jest', 'jest-canvas-mock',
    'jest-expo', 'jest-fetch-mock', 'jest-image-snapshot', 'jest-junit', 'jest-mock',
    'jest-pnp-resolver', 'jest-preset-angular', 'jest-serializer-html', 'jimp', 'jiti', 'joi',
    'jose', 'jquery', 'js-binary-schema-parser', 'js-queue', 'js-string-escape', 'js-yaml',
    'js2xmlparser', 'jsc-safe-url', 'jsdoc-type-pratt-parser', 'jsdom-global', 'jsep',
    'json-2-csv', 'json-bignum', 'json-buffer', 'json-colorizer', 'json-cycle', 'json-diff',
    'json-lexer', 'json-loader', 'json-logic-js', 'json-parse-better-errors',
    'json-parse-even-better-errors', 'json-pointer', 'json-refs', 'json-rpc-2.0',
    'json-rpc-engine', 'json-schema', 'json-schema-compare', 'json-schema-merge-allof',
    'json-schema-ref-resolver', 'json-schema-to-ts', 'json-schema-to-typescript',
    'json-schema-to-typescript-lite', 'json-schema-to-zod', 'json-schema-traverse',
    'json-schema-typed', 'json-source-map', 'json-stream-stringify', 'json-to-pretty-yaml',
    'json2csv', 'json3', 'json5', 'jsonc-eslint-parser', 'jsonc-parser', 'jsonfile', 'jsonify',
    'jsonlines', 'jsonpointer', 'jsonschema', 'jsonwebtoken', 'jsprim', 'jszip', 'just-extend',
    'jws', 'jwt-decode', 'karma', 'katex', 'khroma', 'kill-port', 'kinesis-local', 'klaw',
    'knex', 'known-css-properties', 'konva', 'kubernetes-types', 'kuler', 'ky', 'kysely',
    'labeled-stream-splicer', 'last-call-webpack-plugin', 'launchdarkly-eventsource',
    'lazy-cache', 'leaflet', 'less', 'less-loader', 'level-iterator-stream', 'libnpmexec',
    'lie', 'light-my-request', 'lightningcss', 'linkedom', 'lint-staged', 'liquid-json', 'lit',
    'lit-html', 'livekit-client', 'load-json-file', 'load-yaml-file', 'loader-runner',
    'loader-utils', 'locate-path', 'lodash', 'lodash.zip', 'log', 'log-driver', 'log-node',
    'log-symbols', 'log-update', 'logform', 'longest', 'lossless-json', 'lowercase-keys',
    'lru-cache', 'lru-memoizer', 'lru-queue', 'lucide-react', 'luxon', 'm3u8-parser',
    'magic-string-ast', 'mailparser', 'make-asynchronous', 'make-cancellable-promise',
    'make-dir', 'make-error', 'make-event-props', 'make-fetch-happen', 'manage-path',
    'map-cache', 'map-obj', 'map-visit', 'markdown-escape', 'markdown-escapes',
    'markdown-extensions', 'markdown-it', 'markdown-it-anchor', 'markdown-it-cjk-friendly',
    'markdown-it-task-lists', 'markdown-table', 'markdown-to-jsx', 'markdownlint', 'marked',
    'matchit', 'math-expression-evaluator', 'math-intrinsics', 'math-random', 'mcp-proxy',
    'mdast-util-from-markdown', 'mdast-util-frontmatter', 'mdast-util-gfm',
    'mdast-util-gfm-autolink-literal', 'mdast-util-gfm-footnote',
    'mdast-util-gfm-strikethrough', 'mdast-util-gfm-table', 'mdast-util-gfm-task-list-item',
    'mdast-util-math', 'mdast-util-mdx', 'mdast-util-mdx-expression', 'mdast-util-mdx-jsx',
    'mdast-util-mdxjs-esm', 'mdast-util-to-markdown', 'mdast-util-to-markdown-cjk-friendly',
    'mdurl', 'media-query-parser', 'media-tracks', 'media-typer', 'mem-fs-editor', 'memfs',
    'memoirist', 'memoizee', 'memory-cache', 'memorystream', 'mensch', 'merge-stream', 'merge2',
    'mersenne-twister', 'metaviewport-parser', 'methods', 'metro', 'metro-cache',
    'metro-cache-key', 'metro-config', 'metro-file-map', 'metro-transform-worker',
    'micromark-core-commonmark', 'micromark-extension-frontmatter', 'micromark-extension-math',
    'micromark-factory-destination', 'micromark-factory-label', 'micromark-factory-space',
    'micromark-factory-title', 'micromark-factory-whitespace', 'micromark-util-decode-string',
    'micromark-util-encode', 'micromark-util-events-to-acorn', 'micromark-util-html-tag-name',
    'micromark-util-types', 'mime-db', 'mime-format', 'mimic-response', 'min-document',
    'min-indent', 'mini-css-extract-plugin', 'minimist', 'minimizer-webpack-plugin', 'minipass',
    'minipass-collect', 'minipass-flush', 'mitt', 'mixin-object', 'mjml-head-html-attributes',
    'mjml-image', 'mjml-parser-xml', 'mjml-preset-core', 'mjml-text', 'mjolnir.js', 'mkdirp',
    'ml-array-max', 'ml-array-min', 'ml-array-rescale', 'mobx', 'mocha', 'mocha-junit-reporter',
    'mocha-multi-reporters', 'mock-fs', 'mocked-exports', 'modify-values',
    'module-details-from-path', 'module-not-found-error', 'moment', 'moment-timezone',
    'mongodb-connection-string-url', 'mongoose', 'moo-color', 'morgan', 'morphdom', 'move-file',
    'mpd-parser', 'msgpackr-extract', 'mssql', 'msw', 'msw-storybook-addon', 'multer',
    'multicast-dns-service-types', 'multipasta', 'multistream',
    'mutation-testing-report-schema', 'mux-embed', 'mylas', 'mysql2', 'named-placeholders',
    'namespace-emitter', 'nano-css', 'nano-spawn', 'nano-time', 'nanoevents', 'nanoid',
    'nanospinner', 'napi-build-utils', 'native-promise-only', 'natural-compare',
    'natural-compare-lite', 'nearley', 'negotiator', 'nerf-dart', 'nested-error-stacks',
    'nestjs-pino', 'netmask', 'new-date', 'new-github-release-url', 'next', 'next-router-mock',
    'next-tick', 'nf3', 'nise', 'njwt', 'nlcst-to-string', 'node', 'node-abi',
    'node-abort-controller', 'node-addon-api', 'node-api-headers', 'node-api-version',
    'node-cache', 'node-environment-flags', 'node-exports-info', 'node-fetch',
    'node-fetch-native', 'node-gyp-build', 'node-gyp-build-optional-packages',
    'node-html-markdown', 'node-html-parser', 'node-linux-x64', 'node-mock-http',
    'node-mocks-http', 'node-object-hash', 'node-polyfill-webpack-plugin', 'node-sql-parser',
    'node-stdlib-browser', 'node-stream-zip', 'nodemon', 'non-error', 'normalize-path',
    'normalize-svg-path', 'normalize-url', 'notifications-node-client', 'npm-registry-fetch',
    'npm-run-path', 'nprogress', 'null-loader', 'num2fraction', 'number-allocator', 'numeral',
    'nuxt', 'nwsapi', 'oas-schema-walker', 'oauth', 'oauth-1.0a', 'oauth-sign', 'oauth4webapi',
    'object-component', 'object-copy', 'object-deep-merge', 'object-inspect', 'object-is',
    'object-keys', 'object-path', 'object-sizeof', 'object-treeify', 'object-visit',
    'object.assign', 'object.defaults', 'object.entries', 'object.fromentries',
    'object.getownpropertydescriptors', 'object.groupby', 'object.hasown', 'object.map',
    'object.reduce', 'object.values', 'ofetch', 'ohash', 'oidc-token-hash', 'on-change', 'once',
    'one-time', 'only', 'openapi-fetch', 'openapi-path-templating',
    'openapi-server-url-templating', 'openapi-types', 'openapi-typescript',
    'openapi-typescript-helpers', 'openid-client', 'optimize-css-assets-webpack-plugin', 'ora',
    'original', 'os-shim', 'oxc-parser', 'p-all', 'p-any', 'p-cancelable', 'p-defer', 'p-event',
    'p-is-promise', 'p-limit', 'p-locate', 'p-memoize', 'p-pipe', 'p-queue', 'p-reduce',
    'p-retry', 'p-throttle', 'p-timeout', 'p-try', 'pac-proxy-agent', 'pad-right', 'papaparse',
    'parent-module', 'parenthesis', 'parse-author', 'parse-bmfont-xml', 'parse-cache-control',
    'parse-conflict-json', 'parse-css-color', 'parse-diff', 'parse-entities',
    'parse-git-config', 'parse-github-url', 'parse-gitignore', 'parse-glob', 'parse-headers',
    'parse-json', 'parse-latin', 'parse-listing', 'parse-ms', 'parse-passwd', 'parse-path',
    'parse-png', 'parse-semver', 'parse-svg-path', 'parse-url', 'parse5',
    'parse5-html-rewriting-stream', 'parse5-parser-stream', 'parse5-sax-parser', 'parseley',
    'parseurl', 'partial-json', 'passport', 'passport-google-oauth20', 'passport-oauth2',
    'password-prompt', 'path', 'path-browserify', 'path-data-parser', 'path-exists',
    'path-expression-matcher', 'path-is-inside', 'path-key', 'path-loader', 'path-name',
    'path-platform', 'path-posix', 'path-to-regexp', 'path-type', 'path-unified', 'path2d',
    'pathe', 'pathval', 'peberminta', 'peek-readable', 'peek-stream', 'perfect-debounce', 'pg',
    'pg-connection-string', 'pg-int8', 'pg-query-stream', 'pgsql-ast-parser', 'picospinner',
    'pinkie', 'pinkie-promise', 'pino', 'pino-http', 'pino-pretty', 'pino-std-serializers',
    'piscina', 'pizzip', 'playwright', 'plugin-error', 'pnp-webpack-plugin', 'pofile',
    'points-on-path', 'pony-cause', 'possible-typed-array-names', 'postcss',
    'postcss-color-functional-notation', 'postcss-color-gray', 'postcss-color-hex-alpha',
    'postcss-color-mod-function', 'postcss-color-rebeccapurple', 'postcss-custom-media',
    'postcss-custom-properties', 'postcss-custom-selectors',
    'postcss-double-position-gradients', 'postcss-env-function', 'postcss-html',
    'postcss-image-set-function', 'postcss-import', 'postcss-lab-function',
    'postcss-load-config', 'postcss-loader', 'postcss-merge-rules', 'postcss-nested',
    'postcss-normalize-string', 'postcss-overflow-shorthand', 'postcss-safe-parser',
    'postcss-sass', 'postcss-scss', 'postcss-selector-parser', 'postcss-simple-vars',
    'postcss-unique-selectors', 'postcss-url', 'postcss-values-parser', 'postgres-array',
    'postgres-bytea', 'postgres-date', 'postgres-interval', 'posthtml', 'posthtml-parser',
    'posthtml-render', 'postman-url-encoder', 'preact', 'preact-render-to-string', 'prettier',
    'prettier-plugin-svelte', 'pretty-time', 'priorityqueuejs', 'prisma', 'probe-image-size',
    'proc-log', 'process', 'process-ancestry', 'process-utils', 'proggy', 'progress', 'promise',
    'promise-call-limit', 'promise-inflight', 'promise-polyfill', 'promise-queue',
    'promise-retry', 'promise-worker-transferable', 'promise.allsettled',
    'promise.prototype.finally', 'promise.series', 'prompt', 'prop-types', 'propagate',
    'properties-file', 'property-expr', 'prosemirror-markdown', 'prosemirror-schema-basic',
    'prosemirror-schema-list', 'prosemirror-state', 'prosemirror-trailing-node',
    'proto3-json-serializer', 'protocol-buffers-schema', 'protocols', 'proxy-agent',
    'proxy-agent-negotiate', 'proxy-compare', 'proxy-from-env', 'proxy-memoize', 'publint',
    'pug-error', 'pug-parser', 'pug-runtime', 'puppeteer', 'pure-color', 'pure-rand', 'qjobs',
    'qs', 'query-string', 'querystringify', 'queue', 'queue-lit', 'queue-microtask',
    'queue-tick', 'quick-events', 'quick-lru', 'quill', 'quill-delta', 'quote-js-string',
    'quote-stream', 'radix-vue', 'radix3', 'raf', 'ramda', 'randexp', 'randombytes',
    'randomfill', 'randomstring', 'range-parser', 'raw-body', 'raw-loader', 'rc',
    'rc-config-loader', 'rc-field-form', 'rc-image', 'rc-input-number', 'rc-picker',
    'rc-progress', 'rc-table', 'react', 'react-color', 'react-compiler-runtime', 'react-csv',
    'react-day-picker', 'react-dev-utils', 'react-docgen-typescript', 'react-dom',
    'react-element-to-jsx-string', 'react-error-boundary', 'react-grid-layout',
    'react-helmet-async', 'react-image-crop', 'react-is', 'react-json-tree', 'react-json-view',
    'react-konva', 'react-lifecycles-compat', 'react-markdown', 'react-medium-image-zoom',
    'react-native-fit-image', 'react-native-get-random-values', 'react-native-url-polyfill',
    'react-number-format', 'react-phone-number-input', 'react-property', 'react-redux',
    'react-router', 'react-router-config', 'react-router-dom', 'react-server-dom-webpack',
    'react-smooth', 'react-window-infinite-loader', 'read-binary-file-arch', 'read-cmd-shim',
    'read-only-stream', 'read-package-json-fast', 'read-pkg', 'read-yaml-file',
    'readable-stream', 'readable-web-to-node-stream', 'reading-time', 'recma-parse', 'redent',
    'redis', 'redis-errors', 'redis-parser', 'reduce-css-calc', 'reduce-flatten', 'redux',
    'redux-immutable', 'redux-logger', 'redux-mock-store', 'redux-persist', 'redux-saga',
    'redux-thunk', 'reflect-metadata', 'reflect.getprototypeof', 'reflect.ownkeys',
    'regenerator-runtime', 'regex', 'regex-recursion', 'regex-utilities',
    'regexp-match-indices', 'regexp-tree', 'regexp.prototype.flags', 'regexpp',
    'registry-auth-token', 'registry-url', 'rehype-format', 'rehype-katex', 'rehype-parse',
    'rehype-sanitize', 'rehype-stringify', 'relay-runtime', 'remark-frontmatter', 'remark-math',
    'remark-rehype', 'remend', 'remove-bom-stream', 'remove-markdown',
    'remove-trailing-separator', 'remove-trailing-spaces', 'repeat-string', 'repeating',
    'request', 'request-light', 'request-progress', 'request-promise-core',
    'requestidlecallback', 'require-from-string', 'require-main-filename',
    'requirejs-config-file', 'reselect', 'resize-observer-polyfill', 'resolve-cwd',
    'resolve-dependency-path', 'resolve-from', 'resolve-global', 'resolve-path',
    'resolve-pathname', 'resolve-protobuf-schema', 'resolve-url-loader', 'response-iterator',
    'responselike', 'retext-latin', 'retry-as-promised', 'retry-axios', 'rgb-regex',
    'rgba-regex', 'rgbcolor', 'rimraf', 'rndm', 'roarr', 'robots-parser', 'rolldown', 'rollup',
    'rou3', 'roughjs', 'router', 'rrweb-cssom', 'rrweb-snapshot', 'rss-parser',
    'rst-selector-parser', 'rtl-css-js', 'run-con', 'run-parallel', 'run-queue', 'run-series',
    'rxjs', 's.color', 'safe-json-parse', 'safe-push-apply', 'safe-regex-test', 'safer-buffer',
    'sanitize-html', 'sanitize.css', 'sass', 'sass-embedded', 'sass-embedded-all-unknown',
    'sass-embedded-linux-arm64', 'sass-embedded-linux-musl-arm64',
    'sass-embedded-linux-musl-x64', 'sass-embedded-linux-x64', 'sass-embedded-unknown-all',
    'sass-formatter', 'sass-graph', 'sass-loader', 'sass-lookup', 'sax', 'saxes', 'schema-dts',
    'schema-utils', 'scss-tokenizer', 'scule', 'secure-json-parse', 'seed-random', 'seedrandom',
    'semver', 'sequelize', 'serialize-error', 'serialize-error-cjs', 'set-immediate-shim',
    'set-proto', 'set-value', 'setimmediate', 'setprototypeof', 'sf-symbols-typescript',
    'sharp', 'shasum-object', 'shebang-regex', 'shell-escape', 'shell-quote', 'shelljs',
    'short-unique-id', 'shx', 'signal-exit', 'signal-polyfill', 'signale', 'simple-concat',
    'simple-lru-cache', 'simple-xml-to-json', 'sinon', 'sister', 'sleep-promise', 'slice-ansi',
    'slugify', 'smol-toml', 'smoothscroll-polyfill', 'smtp-address-parser', 'socket.io-client',
    'socket.io-parser', 'socks', 'socks-proxy-agent', 'sonic-boom', 'sort-asc',
    'sort-css-media-queries', 'sort-desc', 'sort-keys', 'sort-keys-length', 'sort-object',
    'sort-object-keys', 'sort-on', 'sort-package-json', 'sorted-array-functions',
    'source-map-loader', 'space-separated-tokens', 'sparkles', 'spawn-command', 'spawnd',
    'spawndamnit', 'spdx-expression-parse', 'split', 'split-array-stream', 'split-string',
    'split2', 'sponge-case', 'sql-escaper', 'sql-formatter', 'sql-highlight', 'sqlite3',
    'sqlstring', 'srcset', 'ssf', 'stackframe', 'standard-as-callback', 'state-toggle',
    'statuses', 'std-env', 'stdout-stream', 'stealthy-require', 'stream', 'stream-browserify',
    'stream-combiner', 'stream-combiner2', 'stream-composer', 'stream-each', 'stream-exhaust',
    'stream-http', 'stream-json', 'stream-length', 'stream-parser', 'stream-promise',
    'stream-replace-string', 'stream-shift', 'stream-slice', 'stream-to-array',
    'strict-url-sanitise', 'string-argv', 'string-byte-length', 'string-convert',
    'string-env-interpolation', 'string-format', 'string-hash', 'string-length',
    'string-split-by', 'string-template', 'string-ts', 'string-width', 'string.fromcodepoint',
    'string.prototype.codepointat', 'string.prototype.includes', 'string.prototype.matchall',
    'string.prototype.padend', 'string.prototype.padstart', 'string.prototype.repeat',
    'string.prototype.trim', 'string.prototype.trimend', 'string.prototype.trimleft',
    'string.prototype.trimright', 'string.prototype.trimstart', 'stringify-entities',
    'stringify-object', 'strip-ansi', 'strip-bom', 'strip-bom-stream', 'strip-bom-string',
    'strip-final-newline', 'strip-indent', 'strip-json-comments', 'strip-literal', 'strnum',
    'strtok3', 'stubborn-fs', 'style-loader', 'style-mod', 'style-search', 'style-to-js',
    'style-to-object', 'style-value-types', 'styled-jsx', 'stylehacks',
    'stylelint-config-recommended', 'stylelint-config-recommended-scss',
    'stylelint-config-standard', 'stylelint-config-standard-scss', 'stylis', 'stylus',
    'stylus-loader', 'subarg', 'suf-log', 'superagent', 'superstruct', 'supports-color',
    'svelte', 'svelte-check', 'svelte-eslint-parser', 'svelte-toolbelt', 'svelte2tsx',
    'svg-pathdata', 'svgo-loader', 'swagger-parser', 'swagger-schema-official',
    'swagger-ui-express', 'swagger2openapi', 'swc-loader', 'swr', 'sylvester',
    'symbol.prototype.description', 'sync-fetch', 'synchronous-promise', 'systemjs', 'tabbable',
    'table', 'tailwind-merge', 'tailwindcss', 'tap-parser', 'tar', 'tar-fs', 'tar-stream',
    'teen_process', 'teex', 'temp-dir', 'temp-file', 'temp-write', 'tempfile',
    'temporal-polyfill', 'tempy', 'terser-webpack-plugin', 'test-exclude', 'test-renderer',
    'text-decoder', 'text-encoding-utf-8', 'text-extensions', 'text-hex', 'text-segmentation',
    'text-table', 'thenify-all', 'thread-loader', 'thread-stream', 'threads', 'three', 'throat',
    'through', 'through2', 'thunky', 'tildify', 'time-zone', 'timed-out', 'timestring',
    'tiny-async-pool', 'tiny-emitter', 'tinycolor2', 'tinypool', 'tinyqueue', 'tiptap-markdown',
    'to-array', 'to-fast-properties', 'to-object-path', 'to-regex', 'to-regex-range',
    'to-through', 'toidentifier', 'token-stream', 'token-types', 'toml', 'toml-eslint-parser',
    'toposort', 'toposort-class', 'tree-sitter-json', 'trim-canvas', 'troika-three-text',
    'true-case-path', 'truncate-json', 'truncate-utf8-bytes', 'ts-algebra', 'ts-custom-error',
    'ts-error', 'ts-essentials', 'ts-interface-checker', 'ts-json-schema-generator',
    'ts-loader', 'ts-log', 'ts-mocha', 'ts-retry-promise', 'tsconfig',
    'tsconfig-paths-webpack-plugin', 'tsdown', 'tslib', 'tsscmp', 'tty-table', 'tunnel-agent',
    'tv4', 'type', 'type-fest', 'typed-array-byte-length', 'typed-array-byte-offset',
    'typed-array-length', 'typed-emitter', 'typedarray', 'typedarray-to-buffer',
    'typedarray.prototype.slice', 'typedoc-plugin-markdown', 'types-ramda', 'types-registry',
    'typesafe-path', 'typescript', 'typescript-eslint', 'typescript-json-schema',
    'typescript-plugin-css-modules', 'ufo', 'uglify-js', 'uglifyjs-webpack-plugin',
    'uid-promise', 'uid-safe', 'unbash', 'unc-path-regex', 'undefsafe', 'underscore',
    'underscore.string', 'undici', 'undici-types', 'unfetch', 'unidiff', 'unified',
    'unimodules-app-loader', 'unionfs', 'uniq', 'unique-stream', 'unique-string',
    'unist-util-find-after', 'universalify', 'unpic', 'unpipe', 'unplugin-vue-components',
    'unquote', 'unset-value', 'until-async', 'untildify', 'unzip-stream', 'url', 'url-loader',
    'url-parse', 'url-parse-lax', 'url-polyfill', 'url-search-params-polyfill',
    'url-to-options', 'urlpattern-polyfill', 'use-memo-one', 'use-sync-external-store',
    'utf8-byte-length', 'util', 'util.promisify', 'utility-types', 'uuid', 'uuid-parse',
    'uuidv7', 'v8-compile-cache', 'v8-compile-cache-lib', 'v8-to-istanbul', 'vali-date',
    'valibot', 'valid-data-url', 'validate-npm-package-license', 'validate.io-array',
    'validate.io-integer-array', 'validate.io-number', 'validator', 'valtio', 'vary',
    'vega-canvas', 'vega-parser', 'vega-runtime', 'vega-time', 'vfile', 'vfile-matter',
    'vfile-sort', 'video.js', 'vinyl', 'vinyl-file', 'vite', 'vite-compatible-readable-stream',
    'vite-node', 'vite-plugin-vue-devtools', 'vitest-canvas-mock', 'vitest-mock-extended',
    'volar-service-css', 'volar-service-html', 'volar-service-typescript', 'volar-service-yaml',
    'vscode-css-languageservice', 'vscode-html-languageservice', 'vscode-json-languageservice',
    'vscode-languageserver-types', 'vue', 'vue-bundle-renderer', 'vue-demi',
    'vue-eslint-parser', 'vue-hot-reload-api', 'vue-inbrowser-compiler-independent-utils',
    'vue-loader', 'vue-resize', 'vue-router', 'vue-style-loader', 'vue-template-compiler',
    'vuex', 'w3c-keyname', 'w3c-xmlserializer', 'walk-sync', 'walk-up-path', 'weak-lru-cache',
    'weak-map', 'weakmap-polyfill', 'weapon-regex', 'web3-providers-http', 'webcrypto-shim',
    'webextension-polyfill', 'webpack', 'webpack-assets-manifest', 'webpack-bundle-analyzer',
    'webpack-cli', 'webpack-dev-middleware', 'webpack-dev-server', 'webpack-hot-middleware',
    'webpack-log', 'webpack-manifest-plugin', 'webpack-merge', 'webpack-node-externals',
    'webpack-sources', 'webpack-subresource-integrity', 'webpack-virtual-modules',
    'webrtc-adapter', 'whatwg-fetch', 'whatwg-url', 'whatwg-url-minimum',
    'whatwg-url-without-unicode', 'which', 'which-pm-runs', 'which-typed-array',
    'why-is-node-running', 'winston', 'winston-transport', 'wkt-parser', 'workbox-strategies',
    'workbox-webpack-plugin', 'workbox-window', 'worker-factory', 'worker-loader',
    'worker-timers-broker', 'worker-timers-worker', 'workerd', 'wouter', 'wrap-ansi',
    'write-json-file', 'write-yaml-file', 'x-is-string', 'xcode', 'xdg-app-paths', 'xml',
    'xml-but-prettier', 'xml-crypto', 'xml-encryption', 'xml-escape', 'xml-formatter', 'xml-js',
    'xml-name-validator', 'xml-naming', 'xml-parse-from-string', 'xml-parser-xo', 'xml-utils',
    'xml2js', 'xmlbuilder', 'xmlbuilder2', 'xmlchars', 'xmlcreate', 'xmldoc', 'xmldom',
    'xstate', 'yaml', 'yaml-ast-parser', 'yaml-eslint-parser', 'yaml-language-server', 'yamljs',
    'yargs', 'yargs-parser', 'yazl', 'yn', 'yocto-queue', 'yocto-spinner', 'youch-core',
    'yuku-parser', 'yup', 'z-schema', 'zip-stream', 'zlibjs', 'zod', 'zod-error',
    'zod-from-json-schema', 'zod-to-json-schema', 'zustand',
])
